### PR TITLE
Bump joda-time to fix bug with java 8 and AWS x-amz-date header 

### PR DESCRIPTION
**Pull request by no-man-is-an-island**
http://stackoverflow.com/questions/32058431/aws-java-sdk-aws-authentication-requires-a-valid-date-or-x-amz-date-header

### CODE REVIEW

**Comment by sbaxter** [comment]
+1

**Comment by cch1** [comment]
I can confirm that this PR fixes the problem with java 1.8.0_60.

**Comment by omarkj** [comment]
I've made another PR which is a bit simpler. Confirmed to work on my local machine against build 1.8.0_60 of Oracle's JVM.

Link: https://github.com/pjstadig/lein-maven-s3-wagon/pull/6

**Comment by trentonstrong** [comment]
Confirmed +1

**Comment by pjstadig** [comment]
Gah! Sorry! My Github notifications are all wacky, and I didn't even know about this PR. I'll take a look at #6!

**Pull request closed without merging**
